"""empty message

Revision ID: 502999de38d7
Revises: 67ad31558f65
Create Date: 2024-09-11 09:42:09.182877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '502999de38d7'
down_revision = '67ad31558f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_report')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('cash_sales',
               existing_type=sa.FLOAT(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.String(length=150), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('role', sa.String(length=150), nullable=False, server_default=""))
        batch_op.add_column(sa.Column('access_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('approved')
        batch_op.drop_column('access_level')
        batch_op.drop_column('role')
        batch_op.drop_column('company')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('cash_sales',
               existing_type=sa.Text(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    op.create_table('_alembic_tmp_report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('opening_balance', sa.FLOAT(), nullable=False),
    sa.Column('cash_sales', sa.TEXT(), nullable=False),
    sa.Column('expenses', sa.FLOAT(), nullable=False),
    sa.Column('closing_balance', sa.FLOAT(), nullable=False),
    sa.Column('receipt_files', sa.TEXT(), nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(length=150), nullable=False),
    sa.Column('transaction_date', sa.DATE(), server_default=sa.text("'2024-08-27'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
