"""Add role, approved, and access_level columns

Revision ID: 67ad31558f65
Revises: 4f09f37ea558
Create Date: 2024-09-11 09:15:48.392226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ad31558f65'
down_revision = '4f09f37ea558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('cash_sales',
               existing_type=sa.FLOAT(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('company', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('access_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('approved')
        batch_op.drop_column('access_level')
        batch_op.drop_column('role')
        batch_op.drop_column('company')

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.alter_column('cash_sales',
               existing_type=sa.Text(),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
