"""empty message

Revision ID: f89d5436be46
Revises: a1f3159bb1d3
Create Date: 2024-10-03 10:17:36.102745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f89d5436be46'
down_revision = 'a1f3159bb1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('remarks', sa.String(length=300), nullable=True),
    sa.Column('files', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shopexpense')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_column('access_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_level', mysql.ENUM('file_download', 'read_only', 'edit_and_download'), nullable=True))
        batch_op.alter_column('role',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('shopexpense',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('report_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('remarks', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('files', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['report.id'], name='shopexpense_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('shop_expense')
    # ### end Alembic commands ###
